### ISSUE TITLE
Example Plugin Bug

### ISSUE THREAD

**Issue by N3mines** [Xi-CAM/Xi-cam#6]
**Describe the bug**
Operations on the Example Plugin don't work consistently

**To Reproduce**
1. Go to 'Example Plugin'
2. Load in catalog 349497da in the DataResourceBrowser
3. Click the checkmarks next to the image
4. Load the result
5. Click the X or checkmarks again.
6. Load the same result despite different checkmarks

**Expected behavior**
The resulting image will not change despite the checkmarks or X's after they've been used a little bit

**Screenshots**
![image](https://user-images.githubusercontent.com/36215232/83692043-172aef80-a5a8-11ea-9b74-92b0c98cba84.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Xi-CAM Version: Most Recent from Installing Xi-CAM for Windows 10 link

**Comment by ronpandolfi** [comment]
Closing after deprecation of old components
