### ISSUE TITLE
Upgrade to pyqtgraph 0.11.0

### ISSUE THREAD

**Issue by birdzix** [Xi-CAM/Xi-cam#9]
Xi-CAM currently supports pyqtgraph 0.10.0. With large changes in 0.11.0, the interfacing to pyqtgraph will need to be refactored.

May take a few months to address this, as it isn't _critical_ (since we can pin to 0.10.0), but it would be beneficial to use the fixes and changes in the new release of pyqtgraph.

**Comment by ronpandolfi** [comment]
completed with https://github.com/Xi-CAM/Xi-cam/pull/8
